baseurl: '/'
permalink: pretty
title: '(주)성지테크'

logo:
  mobile: "images/logo/logo-mobile.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  about:
    output: true
  contact:
    output: true
  announcements:
    output: true
    sort_by: date

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "about"
    values:
      layout: "about"
  - scope:
      path: ""
      type: "contact"
    values:
      layout: "contact"
  - scope:
      path: ""
      type: "announcements"
    values:
      layout: "announcement"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
